language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
before_script: pip install coveralls
script: 
    - "py.test"
    - "coverage run --source=addict setup.py test"
after_success:
    - coveralls
